### ISSUE TITLE
Getting no data downloaded.

### ISSUE THREAD

**Issue by bennettpeter** [garybuhrmaster/tv_grab_zz_sdjson_sqlite#16]
Suddenly today no data is downloaded. Log shows:

Opening the local database
Obtaining authentication token for Schedules Direct
   Schedules Direct account expires on 2021-09-10T09:06:15
   Schedules Direct data last updated on 2020-09-21T14:08:16
Downloading data from Schedules Direct
   downloading account lineups from Schedules Direct
   downloading channel and station maps for lineup USA-MA20453-X 
   downloading station schedule hashes for 480 stations
      downloading schedule hashes for 250 stations in this chunk
      downloading schedule hashes for 230 stations in this chunk
   not downloading daily schedules (data current)
   not downloading programs (data current)
   not downloading programs for supplemental data (data current)
Pruning the local database

This may be related to the forum issue today which says "suddenly getting no MD5 data"
https://forums.schedulesdirect.org/viewtopic.php?f=15&t=3105&p=10171#p10171
Is MD5 used for determining if data is current?

**Comment by garybuhrmaster** [comment]
> Is MD5 used for determining if data is current?

Yes (it is what optimizes the downloads).  It is also a required field in the response(s) of certain requests regardless of any optimization.  Failure to return required fields is going to be an upstream issue(*).

Without knowing that the upstream issues are (which may include there is no schedule data to download or to create MD5 entries for in any case).

I note that the Schedules Direct server is now offline.  I presume someone is looking at the issue.

(*) I suppose the code might be able to be changed try to work around additional upstream "artifacts".  However I am not sure I understand this one well enough yet to know if there is anything that could be changed such that the results might be better (I guess it is some goodness that the grabber fails gracefully rather than crashing when fed invalid data in this case).

**Comment by bennettpeter** [comment]
Thanks for the response, as you noted it looks like they are working on it now.
