### ISSUE TITLE
start attribute on previously-shown tag includes timezone

### ISSUE THREAD

**Issue by mymatenige** [garybuhrmaster/tv_grab_zz_sdjson_sqlite#6]
The output of the start attribute on previously-shown tag currently includes the timezone.  This is causing MythTV to set the airdate to 0000.  For example:

`<previously-shown start="20110904 +0000" />`

Other xmltv grabbers do not include the timezone.  For example with tv_grab_sd_json:

`<previously-shown start="20110904" />`

See https://sourceforge.net/p/xmltv/mailman/message/35408932/ for more info.

**Comment by garybuhrmaster** [comment]
As reported in that discussion, the grabber is following the XMLTV specifications correctly.  It is the application that is the one in error.  And only legacy (no longer supported) versions of MythTV (before commit ff5ab27) have the issue.  In order to provide individuals a limited period to upgrade to a currently support variant of their application (they need to work with their upstream developers and/or distro providers) the ability for fixups to be applied for specific application issues via an environment variable has been made available (see fixups.txt in the repo for details).

**Comment by mymatenige** [comment]
Whilst I don't disagree with your position that it is a client issue, I am still seeing the issue in MythTV 0.28+.  There is a clear difference between the handling of the output of your grabber and tv_grab_zz_sdjson.  I will perform further investigation.

**Comment by garybuhrmaster** [comment]
Be sure your fixes/0.28 version includes 841073e
