### ISSUE TITLE
All shows are listed as season 1

### ISSUE THREAD

**Issue by bennettpeter** [garybuhrmaster/tv_grab_zz_sdjson_sqlite#8]
A few days ago I upgraded to the latest version of tv_grab_zz_sdjson_sqlite. That was also the time when there was a problem with "Not an array reference", issue #7. Since then the listings show all programs as season 1 plus correct episode number. For example Quantico shows as  S1E18 where it should be S2E18. Law and order SVU shows S1E11 instead of S18E11. I don't know if this is a listings problem or a problem with this grabber.

**Comment by garybuhrmaster** [comment]
On Tue, Apr 18, 2017 at 2:24 AM, Peter Bennett <notifications@github.com> wrote:
>
> A few days ago I upgraded to the latest version of tv_grab_zz_sdjson_sqlite. That was also the time when there was a problem with "Not an array reference", issue #7. Since then the listings show all programs as season 1 plus correct episode number. For example Quantico shows as S1E18 where it should be S2E18. Law and order SVU shows S1E11 instead of S18E11. I don't know if this is a listings problem or a problem with this grabber.

This is likely an issue with the grabber due to
other changes to fix (and consolidate) the total
seasons values.  I'll look to see what the fix
needs to be (but I'll check the upstream data
too, because you can never be sure).

Thanks for the notification.

**Comment by garybuhrmaster** [comment]
I *think* this may be an artifact of not reviewing/applying MythTV trac ticket #12786, as this grabber now returns a (better) total season number (origin_zero_season / total_seasons), which matches the XMLTV DTD.  Looking at my listings, Quantico shows S2E18.  However, I build including the patch from #12786.  Can you apply that patch to your local build and check to see if that fixes the problem?

**Comment by bennettpeter** [comment]
Yes - that fixes it. I will update the ticket status and apply it to the MythTV source repository.

Thanks as always for the quick response.

**Comment by garybuhrmaster** [comment]
Thanks for the quick validation.  Depending on whether the patch is backported to all "supported" MythTV versions (which I think still includes back to fixes/0.27) I may need to consider implementing a mitigation to support the older myths.

That is what I get for submitting a patch (nearly) a year ago and then forgetting about it when I am implementing the spec as written in this grabber (and not as some apps implement it).  My bad.

**Comment by bennettpeter** [comment]
I have installed it on master and 0.28. Not sure about whether to do 0.27.

**Comment by garybuhrmaster** [comment]
As (a) this was a MythTV XMLTV parsing problem (which you have now applied the fix for), and (b) I have added the ability (via an environment variable override (see fixups.txt in the repository, or run the grabber with --info to review the capability) to apply fixups for legacy applications that may also incorrectly parse the numbering, I am going to close this issue.  Thank you for reporting the problem.
